/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface components {
  schemas: {
    GetStudentDto: {
      studentId: string;
      fullName: string;
      progress:
        | 'Excellent'
        | 'Good'
        | 'Satisfactory'
        | 'Unsatisfactory'
        | 'Fail';
      birthday: string;
      createdAt: string;
      updatedAt: string;
    };
    CreateStudentDto: {
      fullName: string;
      progress:
        | 'Excellent'
        | 'Good'
        | 'Satisfactory'
        | 'Unsatisfactory'
        | 'Fail';
      birthday: string;
    };
    UpdateStudentDto: {
      fullName?: string;
      progress?:
        | 'Excellent'
        | 'Good'
        | 'Satisfactory'
        | 'Unsatisfactory'
        | 'Fail';
      birthday?: string;
    };
  };
}
