version: "3.7"
services:
  mongo:
    image: "mongo:latest"
    env_file:
      - ./server/.env
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - mongo-volume:/data/db

volumes:
  mongo-volume:
